// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyO1Pl8xpMIhzPyW_P_aWfwzuDM5rWZ9U',
    appId: '1:120773872035:web:0d6bbb88b68d2b7d76b216',
    messagingSenderId: '120773872035',
    projectId: 'clothingappfrontend',
    authDomain: 'clothingappfrontend.firebaseapp.com',
    storageBucket: 'clothingappfrontend.firebasestorage.app',
    measurementId: 'G-JE21HLQ85K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy4eAZOTJ7VyVLQsV8mDArxmt19NNPSUs',
    appId: '1:120773872035:android:1cf8c35b051940f676b216',
    messagingSenderId: '120773872035',
    projectId: 'clothingappfrontend',
    storageBucket: 'clothingappfrontend.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLUt5MtF7-90-ZJSaki5bBJY4mwQGPtPE',
    appId: '1:120773872035:ios:0985f272dd1c784f76b216',
    messagingSenderId: '120773872035',
    projectId: 'clothingappfrontend',
    storageBucket: 'clothingappfrontend.firebasestorage.app',
    iosBundleId: 'com.example.clothingAppFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLUt5MtF7-90-ZJSaki5bBJY4mwQGPtPE',
    appId: '1:120773872035:ios:0985f272dd1c784f76b216',
    messagingSenderId: '120773872035',
    projectId: 'clothingappfrontend',
    storageBucket: 'clothingappfrontend.firebasestorage.app',
    iosBundleId: 'com.example.clothingAppFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyO1Pl8xpMIhzPyW_P_aWfwzuDM5rWZ9U',
    appId: '1:120773872035:web:14b61f41be29e64776b216',
    messagingSenderId: '120773872035',
    projectId: 'clothingappfrontend',
    authDomain: 'clothingappfrontend.firebaseapp.com',
    storageBucket: 'clothingappfrontend.firebasestorage.app',
    measurementId: 'G-LYSZKHHBWF',
  );
}
